### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by CO2-Pool** [RileyCornelius/ChatGPT-Box#1]
Hi, thank you for your project. I successfully tried the chatbot-demo of ESP, but while building your project, the following error appears:
/home/.../ChatGPT-Box/main/services/openai_api.c:8:10: fatal error: openai.h: No such file or directory
    8 | #include "openai.h"
      |          ^~~~~~~~~~
compilation terminated.

**Comment by w-wu14** [comment]
> Hi, thank you for your project. I successfully tried the chatbot-demo of ESP, but while building your project, the following error appears: /home/.../ChatGPT-Box/main/services/openai_api.c:8:10: fatal error: openai.h: No such file or directory 8 | #include "openai.h" | ^~~~~~~~~~ compilation termin
Do you solve this error?

**Comment by RileyCornelius** [comment]
Fixed
